version: "3"

services:
    nginx:
        image: nginx:1.13-alpine
        labels:
            - "traefik.http.routers.tw-checker.rule=Host(`tw-checker.localhost`)"

        volumes:
            - .:/application
            - ./tools/docker/logs/nginx:/var/log/nginx
            - ./tools/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            traefik:
                ipv4_address: 172.16.3.1

    php:
        build: ./tools/docker/php-fpm
        volumes:
            - .:/application
#    ports:
#    - "9000:9000"
        networks:
            traefik:
                ipv4_address: 172.16.3.2
networks:
    traefik:
        name: traefik
        external: true
